#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdpyinfo
Version  : 1.3.2
Release  : 1
URL      : https://www.x.org/releases/individual/app/xdpyinfo-1.3.2.tar.gz
Source0  : https://www.x.org/releases/individual/app/xdpyinfo-1.3.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xdpyinfo-bin
Requires: xdpyinfo-license
Requires: xdpyinfo-man
BuildRequires : pkgconfig(dmx)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xrender)
BuildRequires : pkgconfig(xtst)
BuildRequires : pkgconfig(xxf86dga)
BuildRequires : pkgconfig(xxf86misc)
BuildRequires : pkgconfig(xxf86vm)

%description
xdpyinfo is a utility for displaying information about an X server.
It is used to examine the capabilities of a server, the predefined
values for various parameters used in communicating between clients
and the server, and the different types of screens, visuals, and X11
protocol extensions that are available.

%package bin
Summary: bin components for the xdpyinfo package.
Group: Binaries
Requires: xdpyinfo-license
Requires: xdpyinfo-man

%description bin
bin components for the xdpyinfo package.


%package license
Summary: license components for the xdpyinfo package.
Group: Default

%description license
license components for the xdpyinfo package.


%package man
Summary: man components for the xdpyinfo package.
Group: Default

%description man
man components for the xdpyinfo package.


%prep
%setup -q -n xdpyinfo-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531975794
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1531975794
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/xdpyinfo
cp COPYING %{buildroot}/usr/share/doc/xdpyinfo/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdpyinfo

%files license
%defattr(-,root,root,-)
/usr/share/doc/xdpyinfo/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/xdpyinfo.1
